name: Build Web and Expo Mobile App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  build-web:
    name: Build Vite Web App
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[force-web]') ||
      steps.filter.outputs.web_changed == 'true'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect changes in web app
        id: filter
        run: |
          echo "web_changed=false" >> "$GITHUB_OUTPUT"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^apps/web/' && echo "web_changed=true" >> "$GITHUB_OUTPUT" || true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Web
        run: pnpm --filter @mss-frontend/web build

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/web/dist

  build-android:
    name: Trigger Expo EAS Build (Android)
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[force-android]') ||
      steps.filter.outputs.android_changed == 'true'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect changes in mobile app
        id: filter
        run: |
          echo "android_changed=false" >> "$GITHUB_OUTPUT"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^apps/mobile/' && echo "android_changed=true" >> "$GITHUB_OUTPUT" || true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Expo CLI and EAS CLI
        run: |
          pnpm add -g expo-cli eas-cli
          sudo apt-get update && sudo apt-get install -y jq

      - name: Trigger EAS Build (Android)
        working-directory: apps/mobile
        run: pnpm exec eas build --platform android --non-interactive --profile production
        timeout-minutes: 45
